Mildestone 4: Add Basic UI
digia3d/OOP-school-library pull request #5
Opened 2022-09-29 19:57 UTC by digia3d

In this part of the project I did the following:

> Create an app.rb file with methods that do the following:

- List all books.
- List all people.
- Create a person (teacher or student, not a plain Person).
- Create a book.
- Create a rental.
- List all rentals for a given person id.
- Present the user with a list of options to perform.
- Lets users choose an option.
- If needed, ask for parameters for the option.
- Have a way to quit the app.

> Create main.rb with defined entry point, there is a method called main that is invoked at the end of the file.

2022-09-29 20:37 UTC, KDlamini requested changes
### Hi @digia3d 🙋‍♀️,  

Great work so far! 💯 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

![pugReaching](https://user-images.githubusercontent.com/38088818/193136899-6d376423-7fc3-47ca-8790-d285de3ceeca.gif)

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 20:37 UTC, KDlamini commented on student.rb
>      @classroom = classroom
When I create a student I get the following error.

![image](https://user-images.githubusercontent.com/38088818/193134904-e43a19f2-3366-4667-9427-12a6b22ab19c.png)

- This is due to the arguments passed in the `Student` class. Kindly look into it.

2022-09-29 20:37 UTC, KDlamini commented on app.rb
> +  end
Same thing with creating a teacher. Kindly look into it and make sure that a teacher can be successfully created.

![image](https://user-images.githubusercontent.com/38088818/193135631-730c0853-113d-4880-b829-d76ecb968dea.png)

2022-09-29 20:37 UTC, KDlamini commented on app.rb
> +  person_id = gets.chomp.to_i
NOTE: When the issues are resolved, kindly ensure that all other functionalities associated with `students` and `teachers` work as expected.

- All created students and teachers can be listed successfully
- Rentals can be created using the list of persons (student or teacher) and books
- Rentals can be viewed using the ID of a person

2022-09-30 08:20 UTC, cynthiainga requested changes
Hi @digia3d, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

![](https://user-images.githubusercontent.com/20563252/121369265-4e418880-c901-11eb-848c-1eff06d5a4cf.gif)

 ## Highlights

- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 
- [ ] Good commit messages ✔️ 
- [ ] Used correct Gitflow ✔️ 

 ## Required Changes ♻️

- [x] Please kindly check the comment under the review 👇 👇 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 08:20 UTC, cynthiainga commented on app.rb
> +end
- [ ] Good job by implementing the changes required but there are still some which aren't been addressed yet. As required by the previous reviewer you should ensure that all other functionalities associated with students and teachers work as expected 🙃 🙃 
- [ ] When I try to list rentals by person id I get an error `undefined method id`, so please kindly fix that 😉 

<img width="1133" alt="Screen Shot 2022-09-30 at 09 49 01" src="https://user-images.githubusercontent.com/74501523/193224873-1aadcee7-30e4-4959-b0d5-08af03793591.png">

2022-09-30 09:33 UTC, thecodechaser requested changes
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @digia3d👋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- Gitflow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 09:33 UTC, thecodechaser commented on app.rb
> +end
- [ ] As requested by the previous reviewer, All functionalities of the application should work as expected. When I try to list rentals for a person I see nothing on the screen. Please fix this issue and make sure list rentals work as expected.
![image](https://user-images.githubusercontent.com/83803414/193240586-b8af5b60-57d8-4e21-8727-34e9ce7da52d.png)

2022-09-30 11:36 UTC, m05e5 approved these changes
# Status: ✔️ Project Approved ✔️ 

Hello @digia3d    🔥 

Good job on implementing the reqested changes. You smashed it. Well Done.
Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! 🎉

![goodjob](https://user-images.githubusercontent.com/60631456/130260474-3c2d5e5c-96df-43de-a0db-8d0059c10862.gif)


Now you can merge this branch 🚀 

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

_m05e5_

### 💻 👩🏽‍💻  Happy Coding!  👨🏽‍💻 🖥️

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-30 11:52 UTC, merged